### PR TITLE
Added explicit type arguments to some method calls to work around typ…

### LINKED ISSUE #7: Eclipse compiler (and thus GWT) is unable to resolve some inferred types in Ix source code
Eclipse and GWT compilers are unable to resolve the inferred type arguments in the bodies of `Ix.toMap` and `Ix.toMultimap` methods.

### PR DESCRIPTION
**Pull request by nfekete**
…e inference limitations in Eclipse (and thus GWT) compiler

fixes https://github.com/akarnokd/ixjava/issues/7

### CODE REVIEW

**Comment by akarnokd** [comment]
Maybe GWT uses an old Eclipse compiler? I don't have any issues within Eclips 4.6.

**Comment by akarnokd** [comment]
Also please create a branch instead of 1.x as it will cause merging problems later on.

**Comment by nfekete** [comment]
That's kinda strange, because I am on 4.6.1 (JDT version is 3.12.1v20160907-1200) and it has problem inferring the type parameters on those 4 lines. Maybe it's worth mentioning that it's set to Java 1.8 source compatibility (GWT 2.8 is source level 1.8 by default).

**Comment by nfekete** [comment]
Yes, I just checked, it's only having the problem with source level 1.8.

**Comment by nfekete** [comment]
I'll redo the pull-request from a different branch.

**Comment by akarnokd** [comment]
Type inference is inconsistent between Java versions and between javac and eclipsec.

> I'll redo the pull-request from a different branch.

Thanks.

**Pull request closed without merging**
